### ISSUE TITLE
这个api获得数据好像不是很准

### ISSUE THREAD

**Issue by leozhanghds** [sonichy/WEATHER_DDE_DOCK#13]
之前安装这个插件的时候，简介用的api也是 https://openweathermap.org 
提供的数据。这个网站的实时数据还差不多，但是七天的数据偏差就比较大了，和手机上的天气预报偏差也比较大。建议国内天气直接抓包中央气象站的数据比较准确一点。以山东省烟台市为例：
展示地址是：http://www.nmc.cn/publish/forecast/ASD/yantai.html
----------------------------------------------------------------
获取省份的api：http://www.nmc.cn/f/rest/province  返回一个json，可以拿到山东省的code是ASD；
获取城市的api:   http://www.nmc.cn/f/rest/province/ASD   返回一个json，可以拿到烟台市的code是54765
通过http://www.nmc.cn/publish/forecast/ASD/yantai.html 可以直接调用浏览器打开页面
通过 http://www.nmc.cn/f/rest/real/54765   返回json可以拿到烟台市的天气，风力和预警警报
通过http://www.nmc.cn/f/rest/tempchart/54765  返回json可以拿到前七天和后七天的最高温度和最低温度，以及天气图片（数字表示）
还一个未来七天精确到每两个小时预报的那个太复杂，就算了，好像也用不到那个

**Comment by sonichy** [comment]
谢谢你提供的新天气API，可以重新做一套天气插件，能不能再挖一个搜索城市返回code的API？
一个插件用2套API，emmm，实在是太复杂了。

**Comment by leozhanghds** [comment]
是的，如果合成一套服务的话，可能得需要自己写一个服务去完成这件事。不过有一个规律是这样的：
A+省份的拼音字母缩写就是省份的code，比如  北京的是ABJ，山东的是 ASD，广东的是AGD等等。也就是说，获取省份下城市的code api就是  http://www.nmc.cn/f/rest/province/ + A + 省份缩写
---------------------------------------------------------------------------------------------------------------------
不过有个问题是这样的：
我之前搜天气的api的时候，好像都是新浪天气，openweathermap这样的，不知道为啥中央气象站的数据没人去抓，按说这个应该是很好发现的，不知道是不是不让用呢

**Comment by sonichy** [comment]
应该说是你最先挖到了NMC的天气API。
省、市对应的code准备爬到本地文本，简化流程。

**Comment by leozhanghds** [comment]
是啊，我当初是想自己开发的，不过嘛...懒了就没搞下去，嘿嘿嘿



发自 zhd在 海天鹰 <notifications@github.com>，2019年3月9日 20:07寫到：应该说是你最先挖到了NMC的天气API。

省、市对应的code准备爬到本地文本，简化流程。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sonichy/WEATHER_DDE_DOCK","title":"sonichy/WEATHER_DDE_DOCK","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sonichy/WEATHER_DDE_DOCK"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sonichy in #13: 应该说是你最先挖到了NMC的天气API。\r\n省、市对应的code准备爬到本地文本，简化流程。"}],"action":{"name":"View Issue","url":"https://github.com/sonichy/WEATHER_DDE_DOCK/issues/13#issuecomment-471171634"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/sonichy/WEATHER_DDE_DOCK/issues/13#issuecomment-471171634",

"url": "https://github.com/sonichy/WEATHER_DDE_DOCK/issues/13#issuecomment-471171634",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
