### ISSUE TITLE
Weather icons look upscaled (digitized) on HiDPI screen

### ISSUE THREAD

**Issue by DanyGee** [sonichy/WEATHER_DDE_DOCK#14]
Please try to fix this:
![DeepinScreenshot_select-area_20190412000239](https://user-images.githubusercontent.com/26818551/55996032-849a0380-5cb6-11e9-91d5-10fbd24b2172.png)

App version: 5.6
Deepin version: 15.9.3
Screen size: 55"
Screen resolution: 3840x2160

**Comment by sonichy** [comment]
I do not understand, icon not clear in HiDPI ？
55‘ 3840x2160, you run deepin on TV ?

**Comment by DanyGee** [comment]
Yes, you understand it perfectly - icons not clear at 3840x2160 and desktop scaling x2.
Yep, my workstation is connected to LG OLED TV via HDMI port.
