### ISSUE TITLE
Doesn't work in fashion mode

### ISSUE THREAD

**Issue by NuLogicSystems** [sonichy/WEATHER_DDE_DOCK#19]
I'm using Manjaro (arch) linux.
When the dock is in fashion mode the plugin is not visible, however it shows up when in efficient mode.

Fashion Mode:
![image](https://user-images.githubusercontent.com/10186587/111338264-2cf83580-864d-11eb-8b6e-fc3cdac85a97.png)

Efficient Mode:
![image](https://user-images.githubusercontent.com/10186587/111338504-616bf180-864d-11eb-9661-43e036d98256.png)

**Comment by sonichy** [comment]
The new Fashion Mode of dock has a problem with old code: the icon will become smaller and smaller finally disappear when you resize the dock repeatedly.
And I have not found the bug point. 
And you can found that the official datetime plugin has removed icon in Fashion Mode (text in Fashion Mode, text in Efficient Mode).

**Comment by NuLogicSystems** [comment]
Yea, I noticed that too. It's such a shame that even upstream can't get the official datetime plugin working right either, but it is what it is. It would still be nice to have your plugin work in both modes, in whatever way possible.

Thanks for the quick reply btw, greatly appreciated.
